# -*- coding: utf-8 -*-
"""aula02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ExcAVvwkJgGYOmr0h8CYG9G2HUUVS4aI
"""

resposta = input('você deseja ir a proxima tela? ')
if resposta == 'sim':
  print('voce foi para outra tela')
else:
    print('você saiu do sistema')

nome = input("informe o nome de usuário: ")
sexo = input("informe 'F' para feminino e 'M' para masculino: ").upper()
if(sexo == 'M'):
    sexo = 'o'
elif(sexo == 'F'):
    sexo = 'a'
usuario = int(input('informe o tipo de usuário \n 1 - para amnistrador \n 2 - para usuário comum \n 3 - para membro associado'))
if(usuario == 1):
    usuario = 'administrador do sistema'
elif(usuario == 3):
    usuario = 'membro associado'
elif(usuario == 2):
    usuario = 'usuario comum'
else:
    usuario = 'inexistente'
print(f'seja bem vind{sexo} {nome}, a sua lincença é de {usuario}')